- Media:
    - Jellyfin:
        href: http://jellyfin.aegirshus
        description: Media server
    - Prowlarr:
        href: http://prowlarr.aegirshus
        description: indexer
    - Sonarr:
        href: http://sonarr.aegirshus
        description: TV + Anime
    - Radarr:
        href: http://radarr.aegirshus
        description: movies
    - Bazarr:
        href: http://bazarr.aegirshus
        description: subtitles
    - qBittorrent:
        href: http://qbittorrent.aegirshus
        description: downloader

- Automation:
    - Home Assistant:
        href: http://ha.aegirshus
        description: Home automation

- Documents:
    - Paperless:
        href: http://paperless.aegirshus
        description: Document management

- Security:
    - Wazuh:
        href: http://wazuh.aegirshus
        description: Security monitoring

- Infrastructure:
    - DNS:
        href: http://dns.aegirshus
        description: AdGuard Home
    - Proxy:
        href: http://proxy.aegirshus
        description: Caddy
    - Portainer:
        href: http://portainer.aegirshus
        description: Docker observability